[default]
APPLICATION_NAME="py-sqs-worker"
APPLICATION_VERSION="1.0.0"
COMSUMER_MAX_WORKERS=25
AWS_SQS_REGION_NAME="us-east-1"
AWS_SQS_MAX_NUMBER_OF_MESSAGES=10

[development]
ENV="dev"
AWS_SQS_ENDPOINT_URL="http://localhost:4576"
AWS_SQS_QUEUE_URL="http://localhost:4576/123456789012/dev-sqs-test"

[docker]
ENV="docker"
AWS_SQS_ENDPOINT_URL="http://localstack:4576"
AWS_SQS_QUEUE_URL="http://localstack:4576/123456789012/dev-sqs-test"

[qa]
ENV="qa"
AWS_SQS_ENDPOINT_URL="https://sqs.us-east-1.amazonaws.com"
AWS_SQS_QUEUE_URL="https://sqs.us-east-1.amazonaws.com/123456789012/qa-sqs-test"

[production]
ENV="prod"
COMSUMER_MAX_WORKERS=25
AWS_SQS_ENDPOINT_URL="https://sqs.amazonaws.com"
AWS_SQS_QUEUE_URL="https://sqs.us-east-1.amazonaws.com/123456789012/prod-sqs-test"